"""Fact-bank for 'Threads that carried' — rotating, gated, counted.

Invariant #1 (lesson 319/139): a fact's NUMBER is counted by the engine, never
generated by a model. Candidates come from counted arc fields + vault outcomes,
each carrying an anchor. The HARD GATE admits a candidate only if it carries a
real counted anchor (no naive 'you worked on X') and it is not a duplicate.
Facts age out when their anchor stops resolving (the thread's data changed) or
past a ttl. The UI rotates over the surviving bank, so a thread shows a
different fact over time — bank is larger than what's shown.
"""
from __future__ import annotations

import json
import time
from pathlib import Path

_DAY = 86_400


def passes_gate(cand: dict) -> bool:
    """HARD gate on what gets written. A fact must carry text AND a counted
    anchor with a real value — a description with no number/outcome behind it
    (a 'naive' fact) is rejected. Dedup is handled by key upstream."""
    anchor = cand.get("anchor") or {}
    val = anchor.get("value")
    if val in (None, "", [], [None], [None, None]):
        return False
    return bool(cand.get("text"))


class FactBank:
    """thread -> [ {key, text, anchor, born, seen} ]. One JSON file."""

    def __init__(self, path: Path, ttl_days: int = 45):
        self.path = Path(path)
        self.ttl_s = ttl_days * _DAY
        try:
            self._data: dict[str, list[dict]] = json.loads(self.path.read_text())
        except (OSError, ValueError):
            self._data = {}
        self.admitted = 0
        self.rejected = 0
        self.aged_out = 0

    def refresh(self, thread: str, candidates: list[dict], now: int) -> None:
        """Run this refresh's candidates through the gate; admit new ones, keep
        the born date of ones already banked, and age out anything whose anchor
        no longer appears (data moved on) or that has outlived its ttl."""
        bank = {f["key"]: f for f in self._data.get(thread, [])}
        live: set[str] = set()
        for c in candidates:
            if not passes_gate(c):
                self.rejected += 1
                continue
            key = c["key"]
            live.add(key)
            if key in bank:  # already written — refresh phrasing/anchor + seen
                bank[key].update(text=c["text"], anchor=c["anchor"], seen=now)
            else:  # ADMIT — gate passed, first time
                bank[key] = {**c, "born": now, "seen": now}
                self.admitted += 1
        kept = []
        for key, f in bank.items():
            anchor_gone = key not in live
            expired = (now - f.get("seen", f["born"])) > self.ttl_s
            if anchor_gone or expired:
                self.aged_out += 1
            else:
                kept.append(f)
        kept.sort(key=lambda f: f["born"])  # stable order for rotation
        if kept:
            self._data[thread] = kept
        else:
            self._data.pop(thread, None)

    def rotating(self, thread: str, day: int) -> dict | None:
        """The fact shown today for this thread — rotates so the bank surfaces
        different facts across days without ever showing an ungated one."""
        facts = self._data.get(thread)
        if not facts:
            return None
        return facts[day % len(facts)]

    def count(self, thread: str) -> int:
        return len(self._data.get(thread, []))

    def save(self) -> None:
        try:
            self.path.parent.mkdir(parents=True, exist_ok=True)
            tmp = self.path.with_suffix(".tmp")
            tmp.write_text(json.dumps(self._data, ensure_ascii=False, indent=1))
            tmp.replace(self.path)
        except OSError:
            pass
